function loadSkinMod(path, model)
	if fileExists(path .. "/" .. model .. ".txd") then
		local txd = engineLoadTXD(path .. "/" .. model .. ".txd")

		if txd then
			engineImportTXD(txd, model)
		end
	end

	if fileExists(path .. "/" .. model .. ".dff") then
		local dff = engineLoadDFF(path .. "/" .. model .. ".dff")

		if fileExists(path .. "/" .. model .. ".dff") then
			engineReplaceModel(dff, model)
		end
	end
end

loadSkinMod("custom", 162)
loadSkinMod("custom", 251)
loadSkinMod("custom", 82)
loadSkinMod("custom", 261)
loadSkinMod("custom", 29)
loadSkinMod("custom", 188)
loadSkinMod("custom", 157)
loadSkinMod("custom", 88)
loadSkinMod("custom", 269)
loadSkinMod("custom", 231)
loadSkinMod("custom", 175)
loadSkinMod("custom", 236)
loadSkinMod("custom", 213)
loadSkinMod("custom", 243)
loadSkinMod("custom", 245)
loadSkinMod("custom", 191)
loadSkinMod("custom", 83)
loadSkinMod("custom", 198)
loadSkinMod("custom", 214)

loadSkinMod("custom", 12) -- CsakSimánKrisztián#2525 pp-zte
loadSkinMod("custom", 43) -- pumpedhot#5647 pp-zte

loadSkinMod("groups/graves", 212)
loadSkinMod("groups/graves", 213)
loadSkinMod("groups/graves", 215)
loadSkinMod("groups/graves", 216)
loadSkinMod("groups/graves", 218)

loadSkinMod("groups/turkish", 221)
loadSkinMod("groups/turkish", 253)
loadSkinMod("groups/turkish", 255)
loadSkinMod("groups/turkish", 262)
loadSkinMod("groups/turkish", 263)
loadSkinMod("groups/turkish", 222)
loadSkinMod("groups/turkish", 223)

loadSkinMod("groups/roadman", 233)
loadSkinMod("groups/roadman", 234)
loadSkinMod("groups/roadman", 235)
--loadSkinMod("groups/roadman", 236)
loadSkinMod("groups/roadman", 238)
loadSkinMod("groups/roadman", 239)
loadSkinMod("groups/roadman", 241)
loadSkinMod("groups/roadman", 242)

loadSkinMod("groups/hungarian", 121)
loadSkinMod("groups/hungarian", 122)
loadSkinMod("groups/hungarian", 123)
loadSkinMod("groups/hungarian", 125)
loadSkinMod("groups/hungarian", 128)
loadSkinMod("groups/hungarian", 130)

loadSkinMod("civil", 1)
loadSkinMod("civil", 129)
loadSkinMod("civil", 100)
loadSkinMod("civil", 13)
loadSkinMod("civil", 135)
loadSkinMod("civil", 137)
loadSkinMod("civil", 141)
loadSkinMod("civil", 144)
loadSkinMod("civil", 199)
loadSkinMod("civil", 2)
loadSkinMod("civil", 37)
loadSkinMod("civil", 45)
loadSkinMod("civil", 49)
loadSkinMod("civil", 51)
loadSkinMod("civil", 52)
loadSkinMod("civil", 54)
loadSkinMod("civil", 55)
loadSkinMod("civil", 79)
loadSkinMod("civil", 94)
loadSkinMod("civil", 95)
loadSkinMod("civil", 99)
loadSkinMod("civil", 62)
loadSkinMod("civil", 264)
loadSkinMod("civil", 127)
loadSkinMod("civil", 148)
loadSkinMod("civil", 154)
loadSkinMod("civil", 156)
loadSkinMod("civil", 176)
loadSkinMod("civil", 204)
loadSkinMod("civil", 207)
loadSkinMod("civil", 22)
loadSkinMod("civil", 225)
loadSkinMod("civil", 23)
loadSkinMod("civil", 232)
loadSkinMod("civil", 290)
loadSkinMod("civil", 308)
loadSkinMod("civil", 40)
loadSkinMod("civil", 41)
loadSkinMod("civil", 47)
loadSkinMod("civil", 93)

loadSkinMod("dogs", 256)
loadSkinMod("dogs", 257)
loadSkinMod("dogs", 296)
loadSkinMod("dogs", 297)
loadSkinMod("dogs", 298)
loadSkinMod("dogs", 9)

loadSkinMod("groups/BlasphemyMotor", 38)
loadSkinMod("groups/BlasphemyMotor", 39)
loadSkinMod("groups/BlasphemyMotor", 63)
loadSkinMod("groups/BlasphemyMotor", 140)

loadSkinMod("groups/CromwellMOB", 145)
loadSkinMod("groups/CromwellMOB", 178)
loadSkinMod("groups/CromwellMOB", 246)
loadSkinMod("groups/CromwellMOB", 252)
loadSkinMod("groups/CromwellMOB", 31)

loadSkinMod("groups/FBI", 163)
loadSkinMod("groups/FBI", 164)
loadSkinMod("groups/FBI", 286)

loadSkinMod("groups/PD", 280)
loadSkinMod("groups/PD", 281)
loadSkinMod("groups/PD", 282)
loadSkinMod("groups/PD", 283)
loadSkinMod("groups/PD", 284)
loadSkinMod("groups/PD", 71)
loadSkinMod("groups/PD", 70)


loadSkinMod("groups/RoadPiratesMotor", 196)
loadSkinMod("groups/FBI", 244)
loadSkinMod("groups/RoadPiratesMotor", 247)
loadSkinMod("groups/RoadPiratesMotor", 248)
loadSkinMod("groups/FBI", 186)
loadSkinMod("groups/RoadPiratesMotor", 254)

loadSkinMod("groups/Sheriff", 265)
loadSkinMod("groups/Sheriff", 266)
loadSkinMod("groups/Sheriff", 267)
loadSkinMod("groups/Sheriff", 278)
loadSkinMod("groups/Sheriff", 277)
loadSkinMod("groups/Sheriff", 288)

loadSkinMod("groups/GersonPark", 105)
loadSkinMod("groups/GersonPark", 106)
loadSkinMod("groups/GersonPark", 107)
loadSkinMod("groups/GersonPark", 270)
loadSkinMod("groups/GersonPark", 271)
loadSkinMod("groups/GersonPark", 311)

loadSkinMod("groups/SWAT", 279)
loadSkinMod("groups/SWAT", 285)
loadSkinMod("groups/SWAT", 287)
loadSkinMod("groups/SWAT", 287)

loadSkinMod("groups/FBI", 126)
loadSkinMod("groups/russian", 131)
loadSkinMod("groups/russian", 189)
loadSkinMod("groups/russian", 272)
loadSkinMod("groups/russian", 61)

loadSkinMod("groups/rednecks", 158)
loadSkinMod("groups/rednecks", 159)
loadSkinMod("groups/rednecks", 161)
loadSkinMod("groups/rednecks", 34)
loadSkinMod("groups/rednecks", 200)

loadSkinMod("groups/crips", 120)
loadSkinMod("groups/crips", 205)
loadSkinMod("groups/crips", 237)
loadSkinMod("groups/crips", 77)
loadSkinMod("groups/crips", 97)

loadSkinMod("groups/rpm", 102)
loadSkinMod("groups/rpm", 103)
loadSkinMod("groups/rpm", 104)
loadSkinMod("groups/rpm", 117)
loadSkinMod("groups/rpm", 85)

loadSkinMod("groups/Ambulance", 10)
loadSkinMod("groups/Ambulance", 274)
loadSkinMod("groups/Ambulance", 275)
loadSkinMod("groups/Ambulance", 276)

loadSkinMod("groups/redsands", 114)
loadSkinMod("groups/redsands", 115)
loadSkinMod("groups/redsands", 116)
loadSkinMod("groups/redsands", 118)
loadSkinMod("groups/redsands", 146)

loadSkinMod("groups/parasi", 38)
loadSkinMod("groups/parasi", 39)
loadSkinMod("groups/parasi", 63)
loadSkinMod("groups/parasi", 140)
loadSkinMod("groups/parasi", 120)

loadSkinMod("groups/monolith", 237)
loadSkinMod("groups/monolith", 205)
loadSkinMod("groups/monolith", 97)
loadSkinMod("groups/monolith", 77)

loadSkinMod("groups/carteluj", 75)
loadSkinMod("groups/carteluj", 18)
loadSkinMod("groups/carteluj", 138)
loadSkinMod("groups/carteluj", 139)

--[[loadSkinMod("groups/latin", 108)
loadSkinMod("groups/latin", 109)
loadSkinMod("groups/latin", 115)
loadSkinMod("groups/latin", 116)
loadSkinMod("groups/latin", 118)]]

loadSkinMod("groups/usarmy", 132)
loadSkinMod("groups/usarmy", 133)
loadSkinMod("groups/usarmy", 136)
loadSkinMod("groups/usarmy", 142)
loadSkinMod("groups/usarmy", 143)
loadSkinMod("groups/usarmy", 150)
loadSkinMod("groups/usarmy", 151)
loadSkinMod("groups/usarmy", 152)
loadSkinMod("groups/usarmy", 153)
loadSkinMod("groups/usarmy", 156)
loadSkinMod("groups/usarmy", 301)
loadSkinMod("groups/usarmy", 302)
loadSkinMod("groups/usarmy", 304)
loadSkinMod("groups/usarmy", 166)
loadSkinMod("groups/usarmy", 167)
loadSkinMod("groups/usarmy", 168)
loadSkinMod("groups/usarmy", 169)
loadSkinMod("groups/usarmy", 172)
loadSkinMod("groups/usarmy", 173)