CREATE TABLE `items` (
	`dbID` INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
	`itemId` INT(3) NOT NULL DEFAULT '1',
	`slot` INT(3) NOT NULL DEFAULT '0',
	`amount` INT(11) NOT NULL DEFAULT '1',
	`data1` VARCHAR(1024) DEFAULT '0',
	`data2` VARCHAR(255) DEFAULT '0',
	`data3` VARCHAR(255) DEFAULT '0',
	`nameTag` VARCHAR(64) DEFAULT NULL,
	`serial` INT(11) NOT NULL DEFAULT '0',
	`ownerType` VARCHAR(32) NOT NULL DEFAULT '',
	`ownerId` INT(11) NOT NULL DEFAULT '0'
) ENGINE=MyISAM;

CREATE TABLE `trashes` (
	`trashId` INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
	`posX` FLOAT NOT NULL,
	`posY` FLOAT NOT NULL,
	`posZ` FLOAT NOT NULL,
	`rotZ` FLOAT NOT NULL,
	`interior` INT(3) NOT NULL,
	`dimension` INT(5) NOT NULL,
	`model` INT(11) NOT NULL
) ENGINE=MyISAM;

CREATE TABLE `safes` (
	`dbID` INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
	`posX` FLOAT NOT NULL,
	`posY` FLOAT NOT NULL,
	`posZ` FLOAT NOT NULL,
	`rotZ` FLOAT NOT NULL,
	`interior` INT(3) NOT NULL,
	`dimension` INT(5) NOT NULL,
	`ownerGroup` INT(11) NOT NULL DEFAULT '0'
) ENGINE=MyISAM;

CREATE TABLE `worlditems` (
	`itemDbID` INT(11) NOT NULL PRIMARY KEY,
	`creationDate` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`creatorCharacter` INT(11) NOT NULL,
	`posX` FLOAT NOT NULL,
	`posY` FLOAT NOT NULL,
	`posZ` FLOAT NOT NULL,
	`rotX` FLOAT NOT NULL,
	`rotY` FLOAT NOT NULL,
	`rotZ` FLOAT NOT NULL,
	`interior` INT(3) NOT NULL,
	`dimension` INT(5) NOT NULL,
	`model` INT(11) NOT NULL
) ENGINE=MyISAM;

CREATE TABLE `copiers` (
	`copierId` INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
	`posX` FLOAT NOT NULL,
	`posY` FLOAT NOT NULL,
	`posZ` FLOAT NOT NULL,
	`rotZ` FLOAT NOT NULL,
	`interior` INT(3) NOT NULL,
	`dimension` INT(5) NOT NULL
) ENGINE=MyISAM;